ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS order_type VARCHAR(16) NOT NULL DEFAULT 'LIMIT';

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS time_in_force VARCHAR(16) NOT NULL DEFAULT 'GTC';

ALTER TABLE trades
    ADD COLUMN IF NOT EXISTS liquidity_role VARCHAR(8) NOT NULL DEFAULT 'TAKER';

ALTER TABLE trades
    ADD COLUMN IF NOT EXISTS fee NUMERIC(36, 18) NOT NULL DEFAULT 0;
